CREATE TABLE customers (id serial primary key, first_name text, last_name text);

INSERT INTO customers (first_name, last_name) VALUES ('Hello', 'World');
SELECT pg_sleep(4.5);
INSERT INTO customers (first_name, last_name) VALUES ('Hello', 'World');
SELECT pg_sleep(4.5);
INSERT INTO customers (first_name, last_name) VALUES ('Hello', 'World');
SELECT pg_sleep(4.5);
INSERT INTO customers (first_name, last_name) VALUES ('Hello', 'World');
SELECT pg_sleep(4.5);
INSERT INTO customers (first_name, last_name) VALUES ('Hello', 'World');
SELECT pg_sleep(4.5);
INSERT INTO customers (first_name, last_name) VALUES ('Hello', 'World');
SELECT pg_sleep(4.5);
INSERT INTO customers (first_name, last_name) VALUES ('Hello', 'World');
SELECT pg_sleep(4.5);
INSERT INTO customers (first_name, last_name) VALUES ('Hello', 'World');
SELECT pg_sleep(4.5);
INSERT INTO customers (first_name, last_name) VALUES ('Hello', 'World');
SELECT pg_sleep(4.5);
INSERT INTO customers (first_name, last_name) VALUES ('Hello', 'World');
SELECT pg_sleep(4.5);
INSERT INTO customers (first_name, last_name) VALUES ('Hello', 'World');
SELECT pg_sleep(4.5);
INSERT INTO customers (first_name, last_name) VALUES ('Hello', 'World');
SELECT pg_sleep(4.5);
INSERT INTO customers (first_name, last_name) VALUES ('Hello', 'World');
SELECT pg_sleep(4.5);
INSERT INTO customers (first_name, last_name) VALUES ('Hello', 'World');
SELECT pg_sleep(4.5);
INSERT INTO customers (first_name, last_name) VALUES ('Hello', 'World');
