// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Nextdoor/pg-bifrost.git/transport (interfaces: Batch,BatchFactory)
//
// Generated by this command:
//
//	mockgen -destination mocks/mock_batch.go -package=mocks github.com/Nextdoor/pg-bifrost.git/transport Batch,BatchFactory
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	marshaller "github.com/Nextdoor/pg-bifrost.git/marshaller"
	transport "github.com/Nextdoor/pg-bifrost.git/transport"
	ordered_map "github.com/cevaris/ordered_map"
	gomock "go.uber.org/mock/gomock"
)

// MockBatch is a mock of Batch interface.
type MockBatch struct {
	ctrl     *gomock.Controller
	recorder *MockBatchMockRecorder
	isgomock struct{}
}

// MockBatchMockRecorder is the mock recorder for MockBatch.
type MockBatchMockRecorder struct {
	mock *MockBatch
}

// NewMockBatch creates a new mock instance.
func NewMockBatch(ctrl *gomock.Controller) *MockBatch {
	mock := &MockBatch{ctrl: ctrl}
	mock.recorder = &MockBatchMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatch) EXPECT() *MockBatchMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockBatch) Add(msg *marshaller.MarshalledMessage) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", msg)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockBatchMockRecorder) Add(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockBatch)(nil).Add), msg)
}

// Close mocks base method.
func (m *MockBatch) Close() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Close indicates an expected call of Close.
func (mr *MockBatchMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockBatch)(nil).Close))
}

// CreateTime mocks base method.
func (m *MockBatch) CreateTime() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTime")
	ret0, _ := ret[0].(int64)
	return ret0
}

// CreateTime indicates an expected call of CreateTime.
func (mr *MockBatchMockRecorder) CreateTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTime", reflect.TypeOf((*MockBatch)(nil).CreateTime))
}

// GetPartitionKey mocks base method.
func (m *MockBatch) GetPartitionKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPartitionKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPartitionKey indicates an expected call of GetPartitionKey.
func (mr *MockBatchMockRecorder) GetPartitionKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPartitionKey", reflect.TypeOf((*MockBatch)(nil).GetPartitionKey))
}

// GetPayload mocks base method.
func (m *MockBatch) GetPayload() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayload")
	ret0, _ := ret[0].(any)
	return ret0
}

// GetPayload indicates an expected call of GetPayload.
func (mr *MockBatchMockRecorder) GetPayload() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayload", reflect.TypeOf((*MockBatch)(nil).GetPayload))
}

// GetPayloadByteSize mocks base method.
func (m *MockBatch) GetPayloadByteSize() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayloadByteSize")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetPayloadByteSize indicates an expected call of GetPayloadByteSize.
func (mr *MockBatchMockRecorder) GetPayloadByteSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayloadByteSize", reflect.TypeOf((*MockBatch)(nil).GetPayloadByteSize))
}

// GetTransactions mocks base method.
func (m *MockBatch) GetTransactions() *ordered_map.OrderedMap {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactions")
	ret0, _ := ret[0].(*ordered_map.OrderedMap)
	return ret0
}

// GetTransactions indicates an expected call of GetTransactions.
func (mr *MockBatchMockRecorder) GetTransactions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactions", reflect.TypeOf((*MockBatch)(nil).GetTransactions))
}

// IsEmpty mocks base method.
func (m *MockBatch) IsEmpty() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEmpty")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEmpty indicates an expected call of IsEmpty.
func (mr *MockBatchMockRecorder) IsEmpty() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEmpty", reflect.TypeOf((*MockBatch)(nil).IsEmpty))
}

// IsFull mocks base method.
func (m *MockBatch) IsFull() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFull")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsFull indicates an expected call of IsFull.
func (mr *MockBatchMockRecorder) IsFull() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFull", reflect.TypeOf((*MockBatch)(nil).IsFull))
}

// ModifyTime mocks base method.
func (m *MockBatch) ModifyTime() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyTime")
	ret0, _ := ret[0].(int64)
	return ret0
}

// ModifyTime indicates an expected call of ModifyTime.
func (mr *MockBatchMockRecorder) ModifyTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyTime", reflect.TypeOf((*MockBatch)(nil).ModifyTime))
}

// NumMessages mocks base method.
func (m *MockBatch) NumMessages() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NumMessages")
	ret0, _ := ret[0].(int)
	return ret0
}

// NumMessages indicates an expected call of NumMessages.
func (mr *MockBatchMockRecorder) NumMessages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumMessages", reflect.TypeOf((*MockBatch)(nil).NumMessages))
}

// MockBatchFactory is a mock of BatchFactory interface.
type MockBatchFactory struct {
	ctrl     *gomock.Controller
	recorder *MockBatchFactoryMockRecorder
	isgomock struct{}
}

// MockBatchFactoryMockRecorder is the mock recorder for MockBatchFactory.
type MockBatchFactoryMockRecorder struct {
	mock *MockBatchFactory
}

// NewMockBatchFactory creates a new mock instance.
func NewMockBatchFactory(ctrl *gomock.Controller) *MockBatchFactory {
	mock := &MockBatchFactory{ctrl: ctrl}
	mock.recorder = &MockBatchFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatchFactory) EXPECT() *MockBatchFactoryMockRecorder {
	return m.recorder
}

// NewBatch mocks base method.
func (m *MockBatchFactory) NewBatch(partitionKey string) transport.Batch {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewBatch", partitionKey)
	ret0, _ := ret[0].(transport.Batch)
	return ret0
}

// NewBatch indicates an expected call of NewBatch.
func (mr *MockBatchFactoryMockRecorder) NewBatch(partitionKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewBatch", reflect.TypeOf((*MockBatchFactory)(nil).NewBatch), partitionKey)
}
