name: Lint

env:
  GO_VERSION: '1.20.4'
  LINTER_VERSION: 'v1.52.2'

on: push

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v2
      - name: Cache Vendor
        uses: actions/cache@v2
        env:
          cache-name: cache-vendor-v1
        with:
          path: vendor
          key: ${{ env.cache-name }}-${{ env.GO_VERSION }}-${{ hashFiles('go.mod') }}-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ env.cache-name }}-${{ env.GO_VERSION }}-
            ${{ env.cache-name }}-

      - name: Populate Vendor
        shell: bash
        run: |
          make vendor

      - shell: bash
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@${{ env.LINTER_VERSION }}

      - shell: bash
        run: golangci-lint run --out-format=github-actions